sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sidnaik1975/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sidnaik1975/docker-react npm run test
